config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'confirm'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root :to => 'homes#top'
end

app/models/post.rb
class Post < ApplicationRecord
  attachment :image 
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :place_category, optional: true
  belongs_to :genre_category, optional: true

  validates :place_category_id, presence: true
  validates :genre_category_id, presence: true
  validates :gourme_name, presence: true
  validates :shop_name, presence: true
  validates :price, presence: true
  validates :content, presence: true, length: { maximum: 150 }
  validates :image, presence: true

  enum status: { published: 0, draft: 1 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new  
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @posts = Post.published.includes(:place_category, :genre_category)
    if params[:place_category_id].present?
      @posts = @posts.where(place_category_id: params[:place_category_id])
    end
    if params[:genre_category_id].present?
      @posts = @posts.where(genre_category_id: params[:genre_category_id])
    end
    @posts = @posts.page(params[:page]).reverse_order.per(10)
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.page(params[:page]).per(10).reverse_order
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  def confirm
    @posts = current_user.posts.draft.page(params[:page]).reverse_order
  end

  private
  def post_params
    params.require(:post).permit(:user_id, :place_category_id, :genre_category_id, :gourme_name, :shop_name, :price, :content, :image, :status)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_index.html.erb
<%= form_with method: :get, local: true do |f| %>
  <div class="posts-filter">
    <div class="smfsearch">
      <div>
        <%= label_tag :place_category_id, "球場名" %>
        <%= select_tag :place_category_id,
            options_from_collection_for_select(PlaceCategory.all, :id, :name, params[:place_category_id]),
            include_blank: "すべて" %>
      </div>
      <div>
        <%= label_tag :genre_category_id, "ジャンル" %>
        <%= select_tag :genre_category_id,
            options_from_collection_for_select(GenreCategory.all, :id, :name, params[:genre_category_id]),
            include_blank: "すべて" %>
      </div>
    </div>
    <div>
      <%= submit_tag "検索", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<% if posts.present? %>
  <div class="posts-grid">
    <% posts.each do |post| %>
      <%= link_to post_path(post.id), class: "post-card post-card-link" do %>
        <div class="post-card-image">
          <%= attachment_image_tag post, :image, format: 'jpeg', size: "100x100" %>
        </div>
        <div class="post-card-body">
          <p class="caption"><%= post.user.name %></p>
          <p>球場名：<%= post.place_category.name %></p>
          <p>ジャンル：<%= post.genre_category.name %></p>
          <p class="gourme-name"><%= post.gourme_name %></p>
        </div>
      <% end %>
    <% end %>
  </div>

  <%= paginate posts %>
<% else %>
  <div class="no-post-message">
  <p>投稿がありません</p>
  </div>
<% end %>

app/views/posts/confirm.html.erb
<h1>下書き一覧</h1>
  <%= render 'index', posts: @posts %>    

app/views/posts/edit.html.erb
<div class="form-wrap">
  <h1>投稿編集</h1>
  <!-- エラー表示 -->
  <% if @post.errors.any? %>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <!-- 投稿フォーム -->
  <%= form_with model: @post, local: true, html: { multipart: true } do |f| %>
    <div class="field">
      <%= f.label :place_category_id, "球場名" %><br>
      <%= f.collection_select :place_category_id, PlaceCategory.all, :id, :name, prompt: "選択してください" %>
    </div>
    <div class="field">
      <%= f.label :genre_category_id, "ジャンル" %><br>
      <%= f.collection_select :genre_category_id, GenreCategory.all, :id, :name, prompt: "選択してください" %>
    </div>
    <h4>グルメ名</h4>
      <%= f.text_field :gourme_name %>
    <h4>店名</h4>
      <%= f.text_field :shop_name %>  
    <h4>価格（税込）</h4>
      <%= f.text_field :price %> 円
    <h4>感想</h4>  
      <%= f.text_area :content %>
    <h4>画像</h4>
      <%= f.file_field :image %><br>
    <div class="form-group">
      <%= f.select :status, Post.statuses.keys.map { |k| [t("enums.post.status.#{k}"),k]}, {}, {class: "custom-select w-25 mb-3"} %>
    </div>
    <%= f.submit "保存する" %>    
  <% end %>
</div>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<%= render 'index', posts: @posts %>

app/views/posts/new.html.erb
<div class="form-wrap">
  <h1>新規投稿</h1>
  <!-- エラー表示 -->
  <% if @post.errors.any? %>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <!-- 投稿フォーム -->
  <%= form_with model: @post, local: true, html: { multipart: true } do |f| %>
    <div class="form-group">
      <%= f.label :place_category_id, "球場名", class: "form-label-red" %>
      <%= f.collection_select :place_category_id, PlaceCategory.all, :id, :name, prompt: "選択してください", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :genre_category_id, "ジャンル", class: "form-label-red" %>
      <%= f.collection_select :genre_category_id, GenreCategory.all, :id, :name, prompt: "選択してください", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :gourme_name, "グルメ名", class: "form-label-red" %>
      <%= f.text_field :gourme_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :shop_name, "店舗名", class: "form-label-red" %>
      <%= f.text_field :shop_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :price, "価格（税込）", class: "form-label-red" %>
      <div class="form-inline-wrap">
        <%= f.text_field :price, class: "form-control" %>
        <span class="yen-mark">円</span>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :content, "感想", class: "form-label-red" %>
      <%= f.text_area :content, class: "form-control form-textarea-lg" %>
    </div>
    <div class="form-group">
      <%= f.label :image, "画像", class: "form-label-red" %>
      <%= f.file_field :image, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.select :status, Post.statuses.keys.map { |k| [t("enums.post.status.#{k}"),k] }, {}, { class: "form-control" } %> 
    </div>
    <div class="form-group text-center">
      <%= f.submit "投稿する", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="post-detail-outer">
  <div class="post-detail-card">
    <h1>投稿詳細</h1>
    <!-- エラー表示 -->
    <% if @comment.errors.any? %>
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="post-detail-main">
      <div class="post-detail-image">
        <%= attachment_image_tag @post, :image, format: 'jpeg', size: "180x180" %>
      </div>
      <div class="post-detail-info">
        <div class="post-detail-info-row">
          <div class="post-detail-info-label">ユーザー名</div>
          <div class="post-detail-info-value"><%= @post.user.name %></div>
        </div>
        <div class="post-detail-info-row">
          <div class="post-detail-info-label">球場名</div>
          <div class="post-detail-info-value"><%= @post.place_category.name %></div>
        </div>
        <div class="post-detail-info-row">
          <div class="post-detail-info-label">ジャンル</div>
          <div class="post-detail-info-value"><%= @post.genre_category.name %></div>
        </div>
        <div class="post-detail-info-row">
          <div class="post-detail-info-label">グルメ名</div>
          <div class="post-detail-info-value"><%= @post.gourme_name %></div>
        </div>
        <div class="post-detail-info-row">
          <div class="post-detail-info-label">店舗名</div>
          <div class="post-detail-info-value"><%= @post.shop_name %></div>
        </div>
        <div class="post-detail-info-row">
          <div class="post-detail-info-label">価格（税込）</div>
          <div class="post-detail-info-value"><%= number_with_delimiter(@post.price) %>円</div>
        </div>
        <div class="post-detail-info-row">
          <div class="post-detail-info-label">コメント</div>
          <div class="post-detail-info-value"><%= @post.content %></div>
        </div>
      </div>
    </div>

    <div class="post-detail-actions">
        <div id="favorite-<%= @post.id %>">
          <% if @post.favorited_by?(current_user) %>
            <%= form_with url: post_favorites_path(@post), method: :delete, local: true, class: "favorite-form" do %>
                <button type="submit" class="favorite-link favorited">
                <span class="favorite-icon">♥</span>
                <span class="favorite-count"><%= @post.favorites.count %></span>
                </button>
            <% end %>
          <% else %>
            <%= form_with url: post_favorites_path(@post), method: :post, local: true, class: "favorite-form" do %>
                <button type="submit" class="favorite-link">
                <span class="favorite-icon">♡</span>
                <span class="favorite-count"><%= @post.favorites.count %></span>
                </button>
            <% end %>
          <% end %>
        </div>

        <% if @post.user == current_user %>
          <div class="post-detail-editlinks">
            <%= link_to "投稿の編集", edit_post_path(@post.id), class: "btn btn-outline-primary btn-sm" %>
            <%= form_with url: post_path(@post.id), method: :delete, local: true, html: { onsubmit: "return confirm('本当に削除しますか？');" }, class: "d-inline" do %>
              <%= submit_tag "投稿の削除", class: "btn btn-outline-danger btn-sm ml-2" %>
            <% end %>
          </div>
        <% end %>
      <div class="post-detail-backlink mt-2">
        <%= link_to "投稿一覧へ", posts_path, class: "btn btn-secondary btn-sm" %>
      </div>
    </div>

    <div class="comments">
      <h2>コメント</h2>
      <%= form_with(model: [@post, @comment], local: true) do |f| %>
        <%= f.text_area :content, size: "60x5",placeholder: "コメントを入力してください", class: "form-control form-textarea-lg" %>
        <%= f.submit "コメントする", class: "btn btn-primary btn-sm mt-2" %>
      <% end %>
      <p>コメント件数：<%= @comments.count %></p>
      <% @comments.each do |comment| %>
        <div class="comments-index mb-2">
          <b><%= comment.user.name %></b>
          <span style="font-size:0.9em; color:#888;"> <%= comment.created_at.in_time_zone('Tokyo').strftime('%Y/%m/%d %H:%M') %></span><br>
          <%= comment.content %><br>
          <% if comment.user == current_user %>
            <div class="comment-delete">
              <%= link_to "削除", post_comment_path(comment.post, comment),  data: { turbo_method: :delete }, class: "btn-sm btn-danger" %>
            </div>
          <% end %>
        </div>
      <% end %>
      <%= paginate @comments %>
    </div>
  </div>
</div>